if(location.protocol==='file:'){location.replace('http://127.0.0.1:4173/');}
const $=id=>document.getElementById(id);
const state={file:null,gpxText:null,pointCount:0,distance:0,route:[],stage:1,jobId:null,finalBundle:null};

function hav(a,b){const r=6371,d=Math.PI/180,la=(b[1]-a[1])*d,lo=(b[0]-a[0])*d,q=Math.sin(la/2)**2+Math.cos(a[1]*d)*Math.cos(b[1]*d)*Math.sin(lo/2)**2;return 2*r*Math.asin(Math.sqrt(q))}

function normalizedRoute(width,height){
  if(!state.route.length)return [];
  const xs=state.route.map(p=>p[0]),ys=state.route.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),spanX=Math.max(maxX-minX,1e-9),spanY=Math.max(maxY-minY,1e-9),scale=Math.min(width*.62/spanX,height*.55/spanY),step=Math.max(1,Math.floor(state.route.length/500));
  return state.route.filter((_,i)=>i%step===0||i===state.route.length-1).map(([lon,lat])=>[(lon-(minX+maxX)/2)*scale,-(lat-(minY+maxY)/2)*scale]);
}

function draw(){
  const c=$("terrain"),dpr=devicePixelRatio||1,b=c.getBoundingClientRect();c.width=b.width*dpr;c.height=b.height*dpr;const x=c.getContext("2d");x.scale(dpr,dpr);const w=b.width,h=b.height;x.translate(w/2,h/2+6);x.beginPath();for(let i=0;i<6;i++){const a=Math.PI/3*i,X=Math.cos(a)*Math.min(w*.39,240),Y=Math.sin(a)*Math.min(h*.42,180);i?x.lineTo(X,Y):x.moveTo(X,Y)}x.closePath();x.clip();const g=x.createLinearGradient(0,-180,0,190);g.addColorStop(0,"#90979b");g.addColorStop(.26,"#765438");g.addColorStop(.49,"#506f3e");g.addColorStop(1,"#284c35");x.fillStyle=g;x.fillRect(-w/2,-h/2,w,h);
  for(let y=-170;y<180;y+=9){x.beginPath();for(let X=-250;X<=250;X+=5){const Y=y+Math.sin(X*.065+y*.025)*8+Math.cos(X*.018-y*.05)*5;X===-250?x.moveTo(X,Y):x.lineTo(X,Y)}x.strokeStyle="rgba(237,245,223,.16)";x.stroke()}
  const river=[[-185,95],[-120,65],[-75,80],[-15,48],[35,70],[70,30],[105,22],[140,-5],[180,-55]];x.beginPath();river.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.strokeStyle="#2f74c8";x.lineWidth=5;x.lineCap="round";x.lineJoin="round";x.stroke();
  const trail=normalizedRoute(w,h);if(trail.length){x.beginPath();trail.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.strokeStyle="#db3f31";x.lineWidth=7;x.lineCap="round";x.lineJoin="round";x.stroke();const start=trail[0],end=trail[trail.length-1];x.fillStyle="#db3f31";x.beginPath();x.arc(start[0],start[1],7,0,Math.PI*2);x.fill();x.lineWidth=4;x.beginPath();x.arc(end[0],end[1],10,0,Math.PI*2);x.stroke();x.beginPath();x.arc(end[0],end[1],3,0,Math.PI*2);x.fill()}
}

function sync(){const s=+$('size').value,r=+$('resolution').value,e=+$('elevation').value,p=+$('path').value;$('size-v').textContent=s+' mm';$('resolution-v').textContent=r;$('elevation-v').textContent=e.toFixed(2);$('path-v').textContent=p.toFixed(2)+' mm';$('meta-size').textContent=s+' mm';$('meta-r').textContent='R'+r;$('preview-title').textContent=$('title').value||'未命名徒步';const n=[s!==100,r!==8,e!==1.8,p!==1.6].filter(Boolean).length;$('baseline').className=n?'warn':'pass';$('baseline').textContent=n?'! '+n+' 项工程参数偏离真机基线':'✓ 工程参数采用真机基线'}

function goStage(stage){
  if(stage>1&&!state.file){$('gpx').focus();return}
  state.stage=Math.max(1,Math.min(4,stage));document.body.dataset.stage=state.stage;document.querySelectorAll('.stage-tab').forEach(b=>b.classList.toggle('active',+b.dataset.stage===state.stage));
  const target=$('stage-'+state.stage);target?.scrollIntoView({behavior:'smooth',block:state.stage===1?'start':'center'});
  $('previous').hidden=state.stage<=1;$('next').hidden=state.stage>=4;$('simulate').hidden=state.stage<4;$('download').hidden=state.stage<4||!state.jobId;
  $('next').disabled=state.stage===1&&!state.file;
  const labels={1:'下一步：工程参数',2:'下一步：创意设计',3:'下一步：检查输出'},hints={1:'第 1 步：上传 GPX 后进入工程参数。',2:'第 2 步：确认工程参数，然后进入创意设计。',3:'第 3 步：确认标题与日期，然后检查输出。',4:'第 4 步：生成 Blender 仿真；最终文件生成完成后开放下载。'},titles={2:['工程参数','确认地形、轨迹与地图元素'],3:['创意设计','让标题、日期与作品主题保持一致'],4:['输出检查','先仿真，再生成并下载同一任务的成果']};
  if(labels[state.stage])$('next').innerHTML=labels[state.stage]+' <span>→</span>';$('step-hint').textContent=hints[state.stage]||'';if(titles[state.stage]){document.querySelector('.section-title span').textContent=titles[state.stage][0];document.querySelector('.section-title h2').textContent=titles[state.stage][1]}
}

['size','resolution','elevation','path','title'].forEach(id=>$(id).addEventListener('input',sync));
$('reset').onclick=()=>{$('size').value=100;$('resolution').value=8;$('elevation').value=1.8;$('path').value=1.6;sync()};
document.querySelectorAll('.stage-tab').forEach(b=>b.onclick=()=>goStage(+b.dataset.stage));
$('previous').onclick=()=>goStage(state.stage-1);$('next').onclick=()=>goStage(state.stage+1);

$('gpx').onchange=async e=>{const f=e.target.files[0];if(!f)return;const source=await f.text(),xml=new DOMParser().parseFromString(source,'application/xml'),nodes=[...xml.getElementsByTagNameNS('*','trkpt')],pts=nodes.map(n=>[+n.getAttribute('lon'),+n.getAttribute('lat')]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));if(!pts.length){$('file-facts').textContent='没有找到有效 trkpt 轨迹点';return}state.file=f.name;state.gpxText=source;state.pointCount=pts.length;state.route=pts;state.distance=pts.slice(1).reduce((s,p,i)=>s+hav(pts[i],p),0);state.jobId=null;state.finalBundle=null;$('file-name').textContent=f.name;$('file-facts').textContent=`${pts.length} 个轨迹点 · ${state.distance.toFixed(2)} km`;$('file-action').textContent='已读取';$('next').disabled=false;$('download').hidden=true;$('simulate').disabled=false;$('preview-status').textContent='● GPX 形状已同步';initPreviewSlots();draw()};

function buildJob(){const name=$('title').value||state.file.replace(/\.gpx$/i,''),water=$('water').checked;return {schema_version:'1.2-web',preview:{quick_preview:'gpx_shape_only',final_preview:'pending_blender_render'},route:{name,gpx:state.file,facts:{points:state.pointCount,distance_km:+state.distance.toFixed(3)}},customer_input:{display_date:$('date').value,title:name},engineering:{source:'TrailPrint3D',shape:'HEXAGON',object_size_mm:+$('size').value,terrain_resolution:+$('resolution').value,elevation_scale:+$('elevation').value,path_thickness_mm:+$('path').value,path_scale:.8,single_color_trail:true,element_mode:'SINGLECOLORMODE_REMESH',trailprint_water:{water,big_rivers:water,small_rivers:water,include_ocean:water,river_width:1,water_threshold:1,min_island_area:2,coastline_simplify:.1,merge_into_trailprint_terrain:true},trailprint_elements:{forests:$('forest').checked,forest_threshold:10,city_boundaries:$('city').checked,city_threshold:1},bambu:{outputs_3mf:5,outputs_blend:1,colors:['#3F8E43','#6F5034','#858C91','#7A4A20','#D93025','#2563B8']}},deliverables:{three_mf_count:5,blend_count:1,final_dir:'final'}}}

function initPreviewSlots(){const card=document.querySelector('.preview-card');let gallery=$('view-gallery');if(!gallery){gallery=document.createElement('div');gallery.id='view-gallery';gallery.className='view-gallery placeholders';card.querySelector('.preview-truth').before(gallery)}gallery.innerHTML=['装配透视','顶视关系','侧视高度'].map(label=>`<div class="view-slot"><i></i><span>${label}</span><small>等待 Blender 仿真</small></div>`).join('');let coverage=$('coverage');if(!coverage){coverage=document.createElement('div');coverage.id='coverage';coverage.className='coverage';card.querySelector('.model-meta').before(coverage)}coverage.innerHTML='<b>预计交付 · 5 个 3MF + 1 个 Blender</b><span>01 沙盘地形 · 等待</span><span>02 底座 · 等待</span><span>03 轨迹 · 等待</span><span>04 水系 · 等待</span><span>05 四件同盘 · 等待</span><span>06 Blender · 等待</span>'}

function showPreviewSet(result){const card=document.querySelector('.preview-card'),main=$('render-result'),stamp='?t='+Date.now();main.src=result.preview_url+stamp;card.classList.add('rendered');let gallery=$('view-gallery');gallery.className='view-gallery';gallery.innerHTML='';(result.previews||[]).forEach((view,index)=>{const button=document.createElement('button');button.className=index===0?'active':'';button.innerHTML=`<img src="${view.url+stamp}" alt="${view.label}"><span>${view.label}</span>`;button.onclick=()=>{main.src=view.url+stamp;gallery.querySelectorAll('button').forEach(b=>b.classList.remove('active'));button.classList.add('active')};gallery.appendChild(button)});$('coverage').innerHTML='<b>本次仿真覆盖</b><span class="ready">地形 ✓</span><span class="reference">底座与边框文字 △</span><span class="ready">轨迹 ✓</span><span class="ready">水系 ✓</span><span class="pending">四件同盘 待完整流水线</span><span class="ready">Blender ✓</span>'}

function humanSize(bytes){return bytes>1024*1024?(bytes/1024/1024).toFixed(1)+' MB':Math.ceil(bytes/1024)+' KB'}
function showFinalFiles(result,recovered=false){const coverage=$('coverage');coverage.className='coverage downloads';coverage.innerHTML=`<b>${recovered?'上一次已完成任务 · 可直接下载':'最终交付 · QA 全部通过'}</b>`;result.files.forEach(item=>{const link=document.createElement('a');link.href=item.url;link.download='';link.innerHTML=`<strong>${item.key} ${item.label}</strong><small>${humanSize(item.bytes)} · SHA ${item.sha256.slice(0,8)}…</small><em>PASS · 下载</em>`;coverage.appendChild(link)});const all=document.createElement('a');all.className='bundle';all.href=result.bundle.url;all.download='';all.innerHTML=`<strong>↓ 下载完整 5+1 套装</strong><small>${humanSize(result.bundle.bytes)} · 含 SHA-256 清单</small>`;coverage.appendChild(all)}

async function restoreLatestFinal(){try{const response=await fetch('/api/latest-final');if(!response.ok)return;const result=await response.json();state.jobId=result.job_id;state.finalBundle=result.bundle.url;showFinalFiles(result,true)}catch(_){}}

$('simulate').onclick=async()=>{const button=$('simulate');button.disabled=true;button.textContent='Blender 正在生成…';state.jobId=null;state.finalBundle=null;$('download').hidden=true;$('preview-status').textContent='● TrailPrint3D / Blender 处理中';$('step-hint').textContent='首次生成可能需要数分钟，请保持本地页面开启。';try{const response=await fetch('/api/generate-preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gpx_text:state.gpxText,job:buildJob()})}),result=await response.json();if(!response.ok)throw new Error(result.error||'仿真失败');state.jobId=result.job_id;showPreviewSet(result);$('preview-kind').textContent='Blender 三机位工程仿真 · 非最终切片';$('preview-status').textContent='● Blender 仿真完成';$('preview-status').classList.remove('error');$('step-hint').textContent='仿真已通过。下一步生成同一任务的 5+1 最终文件。';button.textContent='重新仿真';$('download').hidden=false;$('download').disabled=false;$('download').innerHTML='生成最终 5+1 <span>→</span>'}catch(error){const offline=error instanceof TypeError||/fetch/i.test(error.message);$('preview-status').textContent=offline?'● 本地服务未连接':'● 仿真失败';$('preview-status').classList.add('error');$('step-hint').textContent=offline?'请双击 start_local.command，再访问 http://127.0.0.1:4173/，不要直接打开 index.html。':error.message;button.textContent=offline?'检查服务后重试':'重试 Blender 仿真'}finally{button.disabled=false}};

$('download').onclick=async()=>{if(state.finalBundle){location.href=state.finalBundle;return}const button=$('download');button.disabled=true;button.textContent='正在核验并打包…';$('preview-status').textContent='● 最终文件 QA 处理中';try{const response=await fetch('/api/finalize-job',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:state.jobId})}),result=await response.json();if(!response.ok)throw new Error(result.error+(result.failed_checks?.length?'（未通过：'+result.failed_checks.join('、')+'）':''));state.finalBundle=result.bundle.url;showFinalFiles(result);$('preview-kind').textContent='Blender 仿真 + 真机验证交付';$('preview-status').textContent='● 5+1 已生成 · QA PASS';$('preview-status').classList.remove('error');$('step-hint').textContent='最终文件已就绪：可逐件下载，也可下载完整 ZIP。';button.innerHTML='下载完整套装 <span>↓</span>';button.disabled=false}catch(error){$('preview-status').textContent='● 最终生成被阻止';$('preview-status').classList.add('error');$('step-hint').textContent=error.message;button.innerHTML='重试生成最终 5+1 <span>→</span>';button.disabled=false}};

addEventListener('resize',draw);sync();draw();initPreviewSlots();goStage(1);restoreLatestFinal();
